SELECT
    CATEGORY,
    COUNT(*) AS ENTRY_COUNT
FROM
    EXPENSES
GROUP BY
    CATEGORY;

SELECT
    CATEGORY,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM
    EXPENSES
GROUP BY
    CATEGORY;

SELECT
    DEPARTMENT,
    AVG(AMOUNT) AS AVERAGE_AMOUNT
FROM
    EXPENSES
GROUP BY
    DEPARTMENT;

SELECT
    CATEGORY,
    COUNT(*)    AS ENTRY_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    AVG(AMOUNT) AS AVERAGE_AMOUNT
FROM
    EXPENSES
GROUP BY
    CATEGORY;

SELECT
    CATEGORY,
    COUNT(*)    AS ENTRY_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    AVG(AMOUNT) AS AVERAGE_AMOUNT
FROM
    EXPENSES
GROUP BY
    CATEGORY
ORDER BY
    TOTAL_AMOUNT DESC;