DROP TABLE IF EXISTS EXPENSES;

CREATE TABLE EXPENSES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    AMOUNT DECIMAL(10, 2),
    DATE DATE
);